name: Build OpenCV for iOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build OpenCV xcframework
    runs-on: macOS-12
    env:
      OCV_VER: 4.6.0

    steps:
      - name: Tools report
        run: |
          type curl grep sed tr brew cmake git python3 2>&1
          xcode-select -p
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Prepare Cache Key
        run: |
          echo "https://github.com/opencv/opencv/archive/refs/tags/${OCV_VER}.tar.gz" >> cache_key.txt
          
      - name: Cache Downloads
        id: cache-downloads
        uses: actions/cache@v3
        with:
            path: |
              ./cache/
            key: ${{ hashFiles('cache_key.txt') }}

      - name: Download if Needed
        if: steps.cache-downloads.outputs.cache-hit != 'true'
        run: |
            mkdir -p ./cache
            curl -o ./cache/opencv-${OCV_VER}.tar.gz -L "https://github.com/opencv/opencv/archive/refs/tags/${OCV_VER}.tar.gz"
      - name: Extract OpenCV
        run: |
          tar xf ./cache/opencv-${OCV_VER}.tar.gz
          ls -l
      - name: Build OpenCV
        run: |
          python3 opencv-${OCV_VER}/platforms/apple/build_xcframework.py \
                  --framework_name opencv2 \
                  --out ./opencv-build \
                  --iphoneos_archs arm64 \
                  --iphonesimulator_archs x86_64,arm64 \
                  --build_only_specified_archs \
                  --without calib3d \
                  --without dnn \
                  --without features2d \
                  --without flann \
                  --without gapi \
                  --without highgui \
                  --without imgcodecs \
                  --without java \
                  --without js \
                  --without ml \
                  --without objc \
                  --without objdetect \
                  --without photo \
                  --without python \
                  --without stitching \
                  --without ts \
                  --without video \
                  --without videoio \
                  --without world
      - name: Zip xcframework
        run: |
          cd ./opencv-build 
          zip -r opencv-ios-${OCV_VER}.zip opencv2.xcframework
          ls -l
          du -sh opencv-ios-${OCV_VER}.zip
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:        
          retention-days: 90
          if-no-files-found: error
          path:
            opencv-build/opencv-*.zip
